// constants/Data.js
export const PRODUCTS = [
  {
    id: 'p1',
    name: 'ຜັກກາດຂຽວ',
    description: 'ຜັກກາດຂຽວສົດທີ່ປູກຢູ່ໃນສວນຜັກສົດທຸກມື້ ເໝາະສຳລັບປຸງແກງ, ຜັດນ້ຳມັນ ຫຼື ປຸງນ້ຳປາ ເພີ່ມຄວາມອຸດົມສົມບູນໃຫ້ອາຫານຂອງທ່ານ.',
    price: 20000,
    imageUrl: require('../assets/images/vegetable1.jpg'),
    category: 'ຜັກ',
  },
  {
    id: 'p2',
    name: 'ຜັກກາດຂາວ',
    description: 'ຜັກກາດຂາວສົດຈາກສວນທ້ອງຖິ່ນ ມີຄວາມກອບ ແລະ ຮົ່ມລື່ນ ມີວິຕາມິນ C ແລະ ໃຍອາຫານສູງ ເໝາະສຳລັບທຳອາຫານພື້ນເມືອງ ແລະ ອາຫານນາຊາດຕ່າງໆ.',
    price: 18000,
    imageUrl: require('../assets/images/vegetable2.jpg'),
    category: 'ຜັກ',
  },
  {
    id: 'p3',
    name: 'ໝາກກ້ອຍ',
    description: 'ໝາກກ້ອຍຫວານໆ ສົດໃໝ່ ສົ່ງຈາກສວນ ມີໄຟເບີ້ ແລະ ເປັນແຫຼ່ງພະລັງງານຈາກຄາໂບໄຮເດຣດຊັ້ນດີ ເໝາະສຳລັບກິນເປັນຂອງຫວານ ຫຼື ປຸງເປັນເມນູຫວານຕ່າງໆ.',
    price: 25000,
    imageUrl: require('../assets/images/fruit2.jpg'),
    category: 'ໝາກໄມ້',
  },
  {
    id: 'p4',
    name: 'ໝາກກ້ຽງ',
    description: 'ໝາກກ້ຽງສົດໃໝ່ ມີລົດຊາດປະເພດເປັນເອກະລັກ ແລະ ເປັນແຫຼ່ງຂອງວິຕາມິນ C ແລະ ແຄລຊຽມ ເໝາະສຳລັບທຳນ້ຳຜົມ ຫຼື ກິນສົດໆ.',
    price: 30000,
    imageUrl: require('../assets/images/fruit4.jpg'),
    category: 'ໝາກໄມ້',
  },
  {
    id: 'p5_a',
    name: 'ຜັກສະລັດ',
    description: 'ຜັກສະລັດອອກແກນິກ ປູກໂດຍບໍ່ໃຊ້ສານເຄມີ ສົດສະອາດ ແລະ ມີຄຸນຄ່າອາຫານສູງ ເໝາະສຳລັບສະລັດຜັກ ຫຼື ປະກອບເມນູອາຫານເພື່ອສຸຂະພາບ.',
    price: 12000,
    imageUrl: require('../assets/images/vegetable4.jpg'),
    category: 'ຜັກ',
  },
  {
    id: 'p6_a',
    name: 'ໝາກມ່ວງ',
    description: 'ໝາກມ່ວງສຸກຫວານຫອມ ມີລົດຊາດເປັນເອກະລັກ ເປັນແຫຼ່ງຂອງວິຕາມິນ A ແລະ C ເຫຼາະສຳລັບປຸງຂອງຫວານ ນ້ຳຫມາກມ່ວງ ຫຼື ເຮັດເປັນນ້ຳຜົມ.',
    price: 30000,
    imageUrl: require('../assets/images/fruit1.jpg'),
    category: 'ໝາກໄມ້',
  },
  {
    id: 'p7',
    name: 'ຜັກບົ້ງ',
    description: 'ຜັກບົ້ງສົດໆທີ່ປູກຕາມຂອບນ້ຳທ້ອງຖິ່ນ ກອບຫວານ, ອຸດົມສົມບຸນ ແລະ ໃຍອາຫານ ເໝາະສຳລັບແກງສົ້ມ ຜັດ ຫຼື ຈິ່ມນ້ຳຈິ່ມ.',
    price: 8000,
    imageUrl: require('../assets/images/vegetable3.jpg'),
    category: 'ຜັກ',
  },
  {
    id: 'p8',
    name: 'ໝາກແຕ່ງໂມ',
    description: 'ໝາກແຕ່ງໂມຫວານຊື່ນ ມີນ້ຳຫຼາຍ ແລະ ມີປະໂຫຍດໃນການຮັກສານ້ຳໃນຮ່າງກາຍ ເໝາະສຳລັັບການຄາຍຮ້ອນ ໃນວັນອາກາດຮ້ອນ ຫຼື ຈັດສົມບູນອາຫານ.',
    price: 35000,
    imageUrl: require('../assets/images/fruit3.jpg'),
    category: 'ໝາກໄມ້',
  },
];